### PR TITLE
added bin routing logic

### PR DESCRIPTION
**Pull request by westrachel**
Bin routing logic:

- GET /api/bins
    returns an array of all bin objects:
   [{"id":16,"uuid":"679256ea","created_at":"2023-01-26T10:09:04.369Z"}, 
     {"id":15,"uuid":"81605825","created_at":"2023-01-26T10:08:28.405Z"}]

- POST /api/bins
    returns object containing uuid info of the newly created bin like so:
      {"uuid":"679256ea"}

### CODE REVIEW

**Comment by westrachel** [comment]
I think the 3rd line has a bit of redundancy let me fix

**Comment by westrachel** [comment]
^and by line 3 I mean line 5 technically

**Review by lukeoguro — DISMISSED** [review]
🙌

**Review by lukeoguro — COMMENTED** [review]
Will test first

**Review by lukeoguro — APPROVED** [review]
Just tested it — working for me! 🥳  Great job Rachel!!!

**Pull request merged**
