### PR TITLE
Add SQL for psql schema

### PR DESCRIPTION
**Pull request by gcpinckert**

### CODE REVIEW

**Review by lukeoguro — APPROVED** [review]
Awesome Ginni!

**Comment by elguaposalsero** [comment]
Testing webhook

**Comment by elguaposalsero** [comment]
Testing webhook again

**Review by lukeoguro — CHANGES_REQUESTED** [review]
Just realized that there are more than 4 types of request methods lol. might just be better to make this a string not enum.

Screen Shot 2023-01-24 at 23 56 19

**Comment by elguaposalsero** [comment]
test

**Comment by elguaposalsero** [comment]
test

**Review by lukeoguro — APPROVED** [review]
Awesome!

**Comment by gcpinckert** [comment]
New changes:
- `db/pg.js` now connects to the cloud psql db
- `schema.sql` has been updated to remove enumerable type and replace with string (`varchar(10)`) values for http methods
- tests removed from schema file

**Review by elguaposalsero — APPROVED** [review]

**Pull request merged**
